--TO CHECK MISMATCH COLUMN
SELECT NVL(T1.TABLE_NAME,T2.TABLE_NAME)TABLE_NAME,
       NVL(T1.COLUMN_NAME,T2.COLUMN_NAME)COLUMN_NAME
FROM (SELECT TABLE_NAME ,COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND TABLE_NAME ='BANK' ORDER BY COLUMN_ID)T1
FULL JOIN (SELECT TABLE_NAME ,COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND TABLE_NAME ='BANK_BK' ORDER BY COLUMN_ID)T2
ON T1.COLUMN_NAME=T2.COLUMN_NAME
WHERE (T1.COLUMN_NAME IS NULL OR T2.COLUMN_NAME IS NULL);

--------------------------------------------------------------------------------------------------
-- TO CHECK MISMATCH COLUMN
WITH CTE_VCTABLE_1 AS 
(SELECT TABLE_NAME ,COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND TABLE_NAME ='INFORMATION_BKP' ORDER BY COLUMN_ID)
,CTE_VCTABLE_2 AS 
(SELECT TABLE_NAME ,COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND TABLE_NAME ='INFORMATION' ORDER BY COLUMN_ID)
SELECT V1.TABLE_NAME A_TABLE_NAME ,V1.COLUMN_NAME A_COLUMN_NAME,
V2.TABLE_NAME B_TABLE_NAME ,V2.COLUMN_NAME B_COLUMN_NAME,
CASE WHEN V1.COLUMN_NAME IS NULL THEN 'Column Not in A table'
     WHEN V2.COLUMN_NAME IS NULL THEN 'Column Not in B table'
     ELSE 'Available in Both  table'
END VALID_COLUMN_CHECK     
FROM CTE_VCTABLE_1 V1
FULL JOIN CTE_VCTABLE_2 V2 ON V2.COLUMN_NAME=V1.COLUMN_NAME;


CASE 
  WHEN EST.STAFFING_EVENT =''TRM'' OR EST1.EMPLOYEE_STATUS=''Terminated'' THEN NVL(EST.TERMINATION_DATE,EST1.TERMINATION_DATE)
  WHEN EST.STAFFING_EVENT IS NULL THEN EP.EFFECTIVE_DATE
END STAFFING_EVENT_DATE

வரைபடமாக்கப்பட்டது.