
--Edwards dashboard tables truncate script
SELECT 'TRUNCATE TABLE '||UI_SCHEMANAME||'.'||UI_TABLENAME||';','TRUNCATE TABLE '||UI_SCHEMANAME||'.'||UI_SRC_DATA_TABLENAME||';','TRUNCATE TABLE '||UI_SRC_MID_TABLE_NAME||';','TRUNCATE TABLE '||UI_MID_TABLE_NAME||';' FROM ED_EY_TABLES_CONFIG;
--------------------------------------------------------------------------------------------------------------
--Runcontrol tables
SELECT * FROM CLIENT_RUN_CONTROL WHERE CLIENT_ID='1060';--RUN CONTRO NAME (CLIENT_ID, CONTROL_ID, CONTROL_NAME)
SELECT * FROM CLIENT_RUN_CONTROL_STEPS WHERE CLIENT_ID='1060';-- QUERY NAME (STAGE-5,WORK-3,LOAD-4 QUERY ORDER-2) (STEPS ID QUERY ORDER)
SELECT * FROM EXTRACT_TASK;
SELECT * FROM EXTRACT_PROCESS WHERE CLIENT_ID='1060';--EXT FOLDER NAME 
SELECT * FROM TASK_TABLE_LIST;--EXT TABLE NAME
SELECT * FROM USER_QUERY;--ALL ONE CONNECT QUERY
SELECT * FROM CLIENT_TABLE_CATEGORY WHERE CLIENT_ID='1060';-- TABLE NAME SAVE
SELECT * FROM QUERY_TO_TABLE;-- WORK AND STAGE TABLE SAVE 
SELECT * FROM TABLES_IN_USE  WHERE CLIENT_ID='1060';
SELECT * FROM CLIENTS_TABLES;--STAGE TABLE LIST
SELECT * FROM CONV_NAME_TBL;-- CONVERSION NAME TABLE
SELECT * FROM CLIENT_DEST_TBLS;-- (CONVERSION ID ,CLINETID)
SELECT * FROM CLIENT_TABLE_MAP;-- STAGE TABLE NAME CREATE (TRANSFORMATION PROCESS)
SELECT * FROM CLIENT_QUERY_MAP;-- STAGE TABLE NAME MAPPING (TRANSFORMATION PROCESS)
SELECT * FROM CLIENT_COL_MAP;-- COLUMN MAPPING TABLE (TRASFORMATION PROCESS)
SELECT * FROM CLIENT_EXPRESSION;-- EXPRESSION MAPPING (EXPRESSION)
SELECT * FROM CLIENT_XLAT_TBL;-- LKP TABLE NAME 
SELECT * FROM  CLIENT_XLAT_MAP;-- LKP MAPPING
SELECT * FROM CLIENT_RUN_CONTROL_BATCH;-- RUNCONTROL NAME (RUNCONTROL PROCESS)
SELECT * FROM CLIENT_RUNCONTROLEXEC_TBL;-- NEW RUNCONTROL ADDITION TABLE 
SELECT * FROM CLIENT_SCHEDULER;-- NEW SCHEDULER PROCESS
SELECT * FROM OS_EIB_RUNCONTROL_MAP ORDER BY RUNCONTROL_GROUP_ID;--

--------------------------------------------------------------------------------------------------------------------
--Db link scripts

Create database link :-

CREATE DATABASE LINK dblink 
    CONNECT TO remote_user IDENTIFIED BY password
    USING '(DESCRIPTION=
                (ADDRESS=(PROTOCOL=TCP)(HOST=oracledb.example.com)(PORT=1521))
                (CONNECT_DATA=(SERVICE_NAME=service_name))
            )';

CREATE DATABASE LINK MASEKE /*(linkname)*/ CONNECT TO eibp /*(username)*/
IDENTIFIED BY dashb0ard# /*PWD*/ USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=3.231.242.251)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=MSK)))'/*(host)*/;

DROP DATABASE LINK /*(LINK_NAME)*/ ;

-------------------------------------------------------------------------------------------------------------------------
--TO CHECK DATE FORMAT IN ORACLE DATABASE

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-RR';

SELECT *
FROM NLS_SESSION_PARAMETERS
WHERE PARAMETER = 'NLS_DATE_FORMAT';

-------------------------------------------------------------------------------------------------------------

SELECT IFSCCODE,REGEXP_SUBSTR(IFSCCODE, '^[[:alpha:]]+') AS bank_code FROM BANK; -- To get split words ONLY
	
SELECT IFSCCODE,REGEXP_SUBSTR(IFSCCODE, '\D+') AS branch_code FROM BANK;-- To get split words ONLY
	
SELECT IFSCCODE,REGEXP_SUBSTR(IFSCCODE, '\d+') AS branch_code FROM BANK; -- To get Split numbers only

SELECT XMLCAST(XMLAGG(XMLELEMENT(COLUMN_NAME,COLUMN_NAME ||',') ORDER BY COLUMN_ID) AS CLOB) AS xml_element 
FROM ALL_TAB_COLS WHERE OWNER=USER AND TABLE_NAME='EMPLOYEE_SRC_CHANGES' ORDER BY COLUMN_ID;-- MORE THAN 4000 LENGTH OF LISTAGG 


SELECT IDNO FROM BANK WHERE MOD(IDNO, 2) = 0;-- TO FIND EVEN NUMBERS IN ORACLE
SELECT IDNO FROM BANK WHERE MOD(IDNO, 2) <> 0;-- TO FIND ODD NUMBERS IN ORACLE


-------------------------------------------------------------------------------------------------------------

--Hasc survey extension and insert scripts

/*insert scripts */
--INSERT INTO ENROLLMENT_SURVEYS
SELECT A.ENROLLMENT_ID, 
A.SURVEYTYPE_ID,
CURRENT_DATE EFFDT,
CASE WHEN EFFDT=CURRENT_DATE THEN EFFSEQ+1 ELSE 1 END EFFSEQ,
'A' EFFSTATUS,
A.BEGIN_DT,
--A.END_DT OLD_END_DT,
'2024-05-20' END_DT,
A.ENROLLMENT_STATUS,
A.MODIFIED_BY,
CURRENT_TIMESTAMP MODIFIED_DT
FROM ENROLLMENT_SURVEYS A
WHERE 
A.EFFDT =(SELECT MAX(EFFDT) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID ) AND
A.EFFSEQ =(SELECT MAX(EFFSEQ) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID AND EFFDT=A.EFFDT) AND
A.EFFSTATUS='A' AND A.ENROLLMENT_ID='600000' AND A.SURVEYTYPE_ID='8';

---------------------------------------------------------------------------------------------------------------------------------------------------------------
--top of the stack

SELECT * FROM ENROLLMENT_SURVEYS A
WHERE 
A.EFFDT =(SELECT MAX(EFFDT) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID ) AND
A.EFFSEQ =(SELECT MAX(EFFSEQ) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID AND EFFDT=A.EFFDT) AND
A.EFFSTATUS='A' AND A.ENROLLMENT_ID='600000' AND A.SURVEYTYPE_ID='1';

--------------------------------------------------------------------------------------------------------------

--Scheduler insert script

--INSERT INTO CLIENT_SCHEDULER
SELECT '1008'CLIENT_ID, '25'SCHEDULER_ID, '25'TASK_ID, 'FILE_IDENTIFIER'TASK_TYPE,CURRENT_DATE EFFDT,'1' EFFSEQ, 
'A'EFF_STATUS, 'WD to OC-EDW-UK'SCHEDULER_NAME, CURRENT_DATE START_AT, ''END_AT, '0 0/1 * 1/1 * ? *'CRON_CODE, 'Y'IS_ENABLED
FROM CLIENT_SCHEDULER WHERE CLIENT_ID='1000' AND TASK_TYPE='FILE_IDENTIFIER';

--INSERT INTO CLIENT_FILE_IDENTIFY_AND_MOVE
SELECT 
'1008'CLIENT_ID, 'WD to OC-EDW-UK'SCHEDULER_NAME,'D:\sFTP\maseke\Edwards_Implementation\Production\' SOURCE_FOLDER, 
CRITERIA, 'D:\OneConnect\integrationHubFiles\Prod\1008\'TARGET_FOLDER, TASK_TYPE, 
'25'TRIGGER_ID, 'Payroll_Extract*United Kingdom Monthly*.xml''FILEPATTERN,'EDU_UK.xml' OUTPUT_NAME, SUPPORT_FILES, SEQ_ORDER, PGP_ID 
FROM CLIENT_FILE_IDENTIFY_AND_MOVE  WHERE CLIENT_ID='1000';

------------------------------------------------------------------------------------------------------------------

--EDWARDS QUERY COMPARISON
/* TO RUN FOR PRODUCTION ENVIRONMENT*/
SELECT B.CLIENT_ID CLIENT_ID_DEV,C.CLIENT_ID CLIENT_ID_QA,B.QUERY_NAME QUERY_NAME_DEV,C.QUERY_NAME QUERY_NAME_QA,B.QUERY_TEXT QUERY_TEXT_DEV,C.QUERY_TEXT QUERY_TEXT_QA FROM CLIENT_RUN_CONTROL_STEPS A
JOIN (SELECT CLIENT_ID,QUERY_NAME,QUERY_TEXT FROM USER_QUERY A WHERE
                A.EFFDT = (SELECT MAX(EFFDT) FROM USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME) AND
                A.EFFSEQ = (SELECT MAX(EFFSEQ) FROM USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME AND EFFDT = A.EFFDT) AND
                A.EFF_STATUS = 'A' AND A.CLIENT_ID = '1009' /*CLIENT ID USE FOR PRODUCTION*/
           ) B ON B.QUERY_NAME = A.OBJ_ID

JOIN (SELECT CLIENT_ID,QUERY_NAME,QUERY_TEXT FROM ONECONNECT.USER_QUERY A WHERE
                A.EFFDT = (SELECT MAX(EFFDT) FROM ONECONNECT.USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME) AND
                A.EFFSEQ = (SELECT MAX(EFFSEQ) FROM ONECONNECT.USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME AND EFFDT = A.EFFDT) AND
                A.EFF_STATUS = 'A' AND A.CLIENT_ID = '1011' /*CLIENT ID USE FOR (DEV OR QA)*/ 
           ) C ON C.QUERY_NAME = A.OBJ_ID
WHERE A.CLIENT_ID = '1009' AND A.STEPS_ID = '2';