--UMG_EMPLOYEE_NEWHIRE_STAGE

SELECT
A.COUNTRY COUNTRY,
A.PAY_GROUP_ID PAY_GROUP_ID,
A.PAYROLL_ID PAYROLL_ID,
A.EMPLOYEE_ID EMPLOYEE_ID,
EPS.FIRST_NAME FIRST_NAME,
EPS.LAST_NAME LAST_NAME,
--EMP.PAYROLL_ID  EMP_CODE,
COALESCE(EAI.PAYROLL_ID_A,EMP.PAYROLL_ID) EMP_CODE,
EPS.TITLE TITLE,
TO_CHAR(TO_DATE(EPS.BIRTH_DATE,'YYYY-MM-DD'),'MM/DD/YYYY') BIRTH_DATE,
EAI.ORGANIZATION_ONE_NAME_A COMPANY_CODE,
--EAI1.FIELD_VALUE DEPARTMENT,
EAI.ORGANIZATION_THREE_ID_A DEPARTMENT,
--EI.IDENTIFIER_TYPE SIN,
EI1.IDENTIFIER_VALUE SIN,
EI2.IDENTIFIER_TYPE IDENTIFIER_TYPE,
EI2.IDENTIFIER_VALUE IDENTIFIER_VALUE,
NVL(EAL1A.ADDRESS_LINE_DATA,EAL1.ADDRESS_LINE_DATA) STREET1,
--EAL1.ADDRESS_LINE_DATA STREET2,
NVL(EAL2A.ADDRESS_LINE_DATA,EAL2.ADDRESS_LINE_DATA) STREET2,
NVL(EA1.MUNICIPALITY,EA.MUNICIPALITY) CITY,
LKP.CODE STATE,
NVL(EA1.POSTAL_CODE,EA.POSTAL_CODE) POSTAL_CODE,
TO_CHAR(TO_DATE(EAI.HIRE_DATE_A,'YYYY-MM-DD'),'MM/DD/YYYY') HIRE_DATE,
--CASE WHEN EPS.PREFERRED_LANGUAGE = 'English (United States)' THEN 'E' ELSE 'F' END PAYROLL_LANGUAGE,
CASE WHEN EPS.PREFERRED_LANGUAGE = 'English (United States)' THEN 'E' 
	 WHEN EPS.PREFERRED_LANGUAGE LIKE 'French%' THEN 'F' ELSE NULL END PAYROLL_LANGUAGE,
--LKP2.PROVN_CODE BUSINESS_SITE_NAME
LKP2.PROVN_CODE BUSINESS_SITE_REGION,
LKP1.REGION_CODE REGION,
/*CASE WHEN ES.EMPLOYEE_STATUS = 'Active' THEN 'A' WHEN ES.EMPLOYEE_STATUS = 'Inactive' THEN 'I'
	 WHEN ES.EMPLOYEE_STATUS = 'Terminated' THEN 'T' END PAYROLL_STATUS,*/
ES.EMPLOYEE_STATUS EMPLOYEE_STATUS,
ES.TERMINATION_DATE TERMINATION_DATE,
--EP.PAY_RATE_TYPE PAYROLL_TYPE,--LKP_PAYROLL_TYPE
LKP3.PAYROLL_TYPE_CODE PAYROLL_TYPE,
--EP.PAY_CYCLE_HOURS RATE,
--CASE WHEN ESH.FREQUENCY = 'Hourly' THEN ESH.AMOUNT END RATE,
--CASE WHEN EP.PAY_RATE_TYPE = 'Hourly' THEN ESH.AMOUNT END RATE,
CASE WHEN ESH.FREQUENCY = 'Hourly' THEN ESH.AMOUNT END RATE,
--EP.DEFAULT_WEEKLY_HOURS STANDARD_HOURS,
--EP.SCHEDULED_WEEKLY_HOURS STANDARD_HOURS,
CASE WHEN EAI.BUSINESS_UNIT_REFERENCE_ID_A = 'Ingrooves' THEN '86.67' ELSE '75.83' END STANDARD_HOURS,
EP.BUSINESS_TITLE JOB_TITLE,
--ESH.AMOUNT SALARY_PER_PAY,
--TO_CHAR(ESH.AMOUNT/24,'fm9999999.90') SALARY_PER_PAY,
CASE WHEN ESH.FREQUENCY = 'Annual' THEN TO_CHAR(ESH.AMOUNT/24,'fm9999999.90')
     WHEN ESH.FREQUENCY = 'Monthly' THEN TO_CHAR(ESH.AMOUNT/2,'fm9999999.90') END  SALARY_PER_PAY,
--EAI3.FIELD_VALUE COST_CENTRE,
EAI.ORGANIZATION_TWO_ID_A COST_CENTRE,
--CASE WHEN EPE.PAYMENT_TYPE = 'Cheque' THEN 'C' ELSE 'D' END PAYMENT_TYPE,
CASE WHEN EPE.PAYMENT_TYPE = 'Cheque' THEN 'C' 
	-- WHEN EPE.PAYMENT_TYPE = 'Deposit' THEN 'D' ELSE NULL END PAYMENT_TYPE,
	WHEN EPE.PAYMENT_TYPE = 'Direct Deposit' THEN 'D' ELSE NULL END PAYMENT_TYPE,
--EPE.BANK_NAME BANK1,
EPE.BANK_ID_NUMBER BANK1,
EPE.BRANCH_ID_NUMBER BRANCH1,
--EPE.BRANCH_NAME BRANCH1,
EPE.ACCOUNT_NUMBER ACCOUNT1,
EPE.BANK_NAME BANK2,
EPE.BRANCH_NAME BRANCH2,
EPE.ACCOUNT_NUMBER ACCOUNT2,
--EAI1.FIELD_VALUE NEW_DEPARTMENT
EAI.ORGANIZATION_THREE_ID_A NEW_DEPARTMENT,
--ES.EMPLOYEE_STATUS PAY_THIS_PERIOD_FLAG
CASE WHEN ES.EMPLOYEE_STATUS = 'Active' THEN 'YES' END PAY_THIS_PERIOD_FLAG
,CASE WHEN EAI.BUSINESS_UNIT_REFERENCE_ID_A LIKE '%Ingrooves%' OR EAI.BUSINESS_UNIT_NAME_A LIKE '%Ingrooves%' THEN 'N' else 'H' END BRANCH
,CASE WHEN EAI.BUSINESS_UNIT_REFERENCE_ID_A LIKE '%Ingrooves%' OR EAI.BUSINESS_UNIT_NAME_A LIKE '%Ingrooves%' THEN 'N' else 'H' END NEW_BRANCH
,NULL ONE_TAX_FORM_FLAG
,NULL POS_EFFDT
,NULL WORKER_TYPE
,NULL OLD_HIREDT
--,NULL CCRA_BN_MRQ_ID
--CASE WHEN EP.WORKER_TYPE = 'Fixed_Term' THEN '2' ELSE '1' END CCRA_BN_MRQ_ID
--,CASE WHEN EP.WORKER_TYPE = 'Fixed_Term' OR EP.WORKER_TYPE = 'Intern_Coop' THEN 2  ELSE 1 END CCRA_BN_MRQ_ID
,CASE WHEN A.STAFFING_EVENT = 'HIR' THEN 2 ELSE 1 END CCRA_BN_MRQ_ID
,NULL STAAFFING_EVENT
,ES.PRIMARY_TERMINATION_REASON PRIMARY_TERMINATION_REASON
,'NH' TYPE 
,NULL ROE_REASON_CODE

FROM UMG_EMPLOYEE_MASTER_WORK A

LEFT JOIN EMPPERSONAL EPS ON A.PAY_GROUP_ID = EPS.PAY_GROUP_ID AND A.EMPLOYEE_ID = EPS.EMPLOYEE_ID AND EPS.EFFECTIVESTATUS = 'A'
AND EPS.MS$LOADID = A.MS$LOADID

LEFT JOIN UMG_EMP_ADD_INFO_WORK EAI ON A.PAY_GROUP_ID = EAI.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAI.EMPLOYEE_ID

LEFT JOIN EMPIDENTIFIER EI ON A.PAY_GROUP_ID = EI.PAY_GROUP_ID AND A.EMPLOYEE_ID = EI.EMPLOYEE_ID AND EI.EFFECTIVESTATUS = 'A'
AND EI.IDENTIFIER_TYPE = 'Social Insurance Number (SVNR)' AND A.MS$LOADID = EI.MS$LOADID

LEFT JOIN EMPIDENTIFIER EI1 ON A.PAY_GROUP_ID = EI1.PAY_GROUP_ID AND A.EMPLOYEE_ID = EI1.EMPLOYEE_ID AND EI1.EFFECTIVESTATUS = 'A'
AND EI1.IDENTIFIER_TYPE = 'Social Insurance Number (SIN)' AND A.MS$LOADID = EI1.MS$LOADID

LEFT JOIN EMPIDENTIFIER EI2 ON A.PAY_GROUP_ID = EI2.PAY_GROUP_ID AND A.EMPLOYEE_ID = EI2.EMPLOYEE_ID AND EI2.EFFECTIVESTATUS = 'A'
 AND A.MS$LOADID = EI2.MS$LOADID

LEFT OUTER JOIN EMPADDRESSLINEDATA EAL1 ON (A.PAY_GROUP_ID = EAL1.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL1.EMPLOYEE_ID 
AND EAL1.EFFECTIVESTATUS = 'A' AND EAL1.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_1' AND EAL1.ADDRESSSEQUENCENUMBER = '1' AND A.MS$LOADID = EAL1.MS$LOADID)

LEFT OUTER JOIN EMPADDRESSLINEDATA EAL1A ON (A.PAY_GROUP_ID = EAL1A.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL1A.EMPLOYEE_ID 
AND EAL1A.EFFECTIVESTATUS = 'A' AND EAL1A.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_1' AND EAL1A.ADDRESSSEQUENCENUMBER = '2' AND A.MS$LOADID = EAL1A.MS$LOADID)

LEFT OUTER JOIN EMPADDRESSLINEDATA EAL2 ON (A.PAY_GROUP_ID = EAL2.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL2.EMPLOYEE_ID 
AND EAL2.EFFECTIVESTATUS = 'A' AND EAL2.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_2' AND EAL2.ADDRESSSEQUENCENUMBER = '1' AND A.MS$LOADID = EAL2.MS$LOADID)

LEFT OUTER JOIN EMPADDRESSLINEDATA EAL2A ON (A.PAY_GROUP_ID = EAL2A.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL2A.EMPLOYEE_ID 
AND EAL2A.EFFECTIVESTATUS = 'A' AND EAL2A.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_2' AND EAL2A.ADDRESSSEQUENCENUMBER = '2' AND A.MS$LOADID = EAL2A.MS$LOADID)

LEFT JOIN EMPADDRESS EA ON A.PAY_GROUP_ID = EA.PAY_GROUP_ID AND A.EMPLOYEE_ID = EA.EMPLOYEE_ID AND EA.EFFECTIVESTATUS = 'A' AND
EA.ADDRESSSEQUENCENUMBER = '1' AND EA.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPADDRESS EA1 ON A.PAY_GROUP_ID = EA1.PAY_GROUP_ID AND A.EMPLOYEE_ID = EA1.EMPLOYEE_ID AND EA1.EFFECTIVESTATUS = 'A' AND
EA1.ADDRESSSEQUENCENUMBER = '2' AND EA1.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPPOSITION EP ON A.PAY_GROUP_ID = EP.PAY_GROUP_ID AND A.EMPLOYEE_ID = EP.EMPLOYEE_ID AND EP.EFFECTIVESTATUS = 'A'
AND EP.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPSTATUS ES ON A.PAY_GROUP_ID = ES.PAY_GROUP_ID AND A.EMPLOYEE_ID = ES.EMPLOYEE_ID AND ES.EFFECTIVESTATUS = 'A'
AND ES.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPPAYMENTELECTION EPE ON A.PAY_GROUP_ID = EPE.PAY_GROUP_ID AND A.EMPLOYEE_ID = EPE.EMPLOYEE_ID AND EPE.EFFECTIVESTATUS = 'A'
AND EPE.MS$LOADID = A.MS$LOADID

LEFT JOIN UMG_SALARYHOURLYPLANS_W_WORK ESH ON A.PAY_GROUP_ID = ESH.PAY_GROUP_ID AND A.EMPLOYEE_ID = ESH.EMPLOYEE_ID AND ESH.EFFECTIVESTATUS = 'A'
AND ESH.MS$LOADID = A.MS$LOADID

LEFT JOIN TBL_PROVINCE_LKP LKP ON LKP.DESCRIPTION = NVL(EA1.REGION,EA.REGION)

LEFT JOIN TBL_REGION_LKP LKP1 ON LKP1.REGION_DESCRIPTION = NVL(EA1.REGION,EA.REGION)

--LEFT JOIN TBL_PROVN_EMPLYMNT_LKP LKP2 ON LKP2.PROVN_NAME = EA.REGION
LEFT JOIN TBL_PROVN_EMPLYMNT_LKP LKP2 ON LKP2.PROVN_NAME = EP.BUSINESS_SITE_REGION

--LEFT JOIN TBL_PAYROLLTYPE_LKP LKP3 ON LKP3.PAYROLL_TYPE = EP.PAY_RATE_TYPE
LEFT JOIN TBL_PAYROLLTYPE_LKP LKP3 ON LKP3.PAYROLL_TYPE = ESH.FREQUENCY

LEFT JOIN TBL_EMP_CODE EMP ON A.EMPLOYEE_ID = EMP.EMPLOYEE_ID 

WHERE A.STAFFING_EVENT IN ('HIR','PGI','PCI')

UNION

SELECT
A.COUNTRY COUNTRY,
A.PAY_GROUP_ID PAY_GROUP_ID,
A.PAYROLL_ID PAYROLL_ID,
A.EMPLOYEE_ID EMPLOYEE_ID,
--EPS.FIRST_NAME FIRST_NAME,
--EPS.LAST_NAME LAST_NAME,
--A.LEGAL_FIRST_NAME FIRST_NAME,
--A.LEGAL_LAST_NAME LAST_NAME,
COALESCE(EPS.FIRST_NAME,EAI.FIRST_NAME_C,EAI.FIRST_NAME_A) FIRST_NAME,
COALESCE(EPS.LAST_NAME,EAI.LAST_NAME_C,EAI.LAST_NAME_A) LAST_NAME,
EMP.PAYROLL_ID EMP_CODE,
EPS.TITLE TITLE,
--TO_CHAR(EPS.BIRTH_DATE) BIRTH_DATE,
TO_CHAR(TO_DATE(EPS.BIRTH_DATE,'YYYY-MM-DD'),'MM/DD/YYYY') BIRTH_DATE,
EAI.ORGANIZATION_ONE_NAME_C COMPANY_CODE,
--EAI1.FIELD_VALUE DEPARTMENT,
EAI.ORGANIZATION_THREE_ID_C DEPARTMENT,
--EI.IDENTIFIER_TYPE SIN,
EI1.IDENTIFIER_VALUE SIN,
EI2.IDENTIFIER_TYPE IDENTIFIER_TYPE,
EI2.IDENTIFIER_VALUE IDENTIFIER_VALUE,
NVL(EAL1A.ADDRESS_LINE_DATA,EAL1.ADDRESS_LINE_DATA) STREET1,
--EAL1.ADDRESS_LINE_DATA STREET2,
NVL(EAL2A.ADDRESS_LINE_DATA,EAL2.ADDRESS_LINE_DATA) STREET2,
NVL(EA1.MUNICIPALITY,EA.MUNICIPALITY) CITY,
LKP.CODE STATE,
NVL(EA1.POSTAL_CODE,EA.POSTAL_CODE) POSTAL_CODE,
TO_CHAR(EAI.HIRE_DATE_C) HIRE_DATE,
--CASE WHEN EPS.PREFERRED_LANGUAGE = 'English (United States)' THEN 'E' ELSE 'F' END PAYROLL_LANGUAGE,
CASE WHEN EPS.PREFERRED_LANGUAGE = 'English (United States)' THEN 'E' 
	 WHEN EPS.PREFERRED_LANGUAGE LIKE 'French%' THEN 'F' ELSE NULL END PAYROLL_LANGUAGE,
--LKP2.PROVN_CODE BUSINESS_SITE_NAME,
LKP2.PROVN_CODE BUSINESS_SITE_REGION,
LKP1.REGION_CODE REGION,
/*CASE WHEN ES.EMPLOYEE_STATUS = 'Active' THEN 'A' WHEN ES.EMPLOYEE_STATUS = 'Inactive' THEN 'I'
WHEN ES.EMPLOYEE_STATUS = 'Terminated' THEN 'T' END PAYROLL_STATUS,*/
/*CASE WHEN COALESCE(ES.EMPLOYEE_STATUS,ES1.EMPLOYEE_STATUS) = 'Active' THEN 'A' WHEN COALESCE(ES.EMPLOYEE_STATUS,ES1.EMPLOYEE_STATUS) = 'Inactive' THEN 'I'
WHEN COALESCE(ES.EMPLOYEE_STATUS,ES1.EMPLOYEE_STATUS) = 'Terminated' THEN 'T' 
WHEN A.STAFFING_EVENT = 'LOA' OR ES.EMPLOYEE_STATUS = 'OnLeave' OR ES.EMPLOYEE_STATUS = 'OnPaidLeave' THEN 'L'
--WHEN COALESCE(A.STAFFING_EVENT,CAST('NULL' AS NVARCHAR2(5))) NOT IN ('HIR','PGI','PCI','TRM','LOA') THEN 'A' 
END PAYROLL_STATUS,*/
ES.EMPLOYEE_STATUS EMPLOYEE_STATUS,
ES.TERMINATION_DATE TERMINATION_DATE,
--EP.PAY_RATE_TYPE PAYROLL_TYPE,--LKP_PAYROLL_TYPE
CASE WHEN COALESCE(A.STAFFING_EVENT,CAST('NULL' AS NVARCHAR2(5))) NOT IN ('TRM') THEN LKP3.PAYROLL_TYPE_CODE END PAYROLL_TYPE,
--EP.PAY_CYCLE_HOURS RATE,
CASE WHEN ESH.FREQUENCY = 'Hourly' THEN ESH.AMOUNT END RATE,

CASE WHEN EP.PAY_CYCLE_HOURS IS NOT NULL AND (EAI.BUSINESS_UNIT_REFERENCE_ID_C = 'Ingrooves' OR EAI.BUSINESS_UNIT_REFERENCE_ID_A = 'Ingrooves') THEN '86.67' 
     WHEN EP.PAY_CYCLE_HOURS IS NOT NULL AND (EAI.BUSINESS_UNIT_REFERENCE_ID_C <> 'Ingrooves' OR EAI.BUSINESS_UNIT_REFERENCE_ID_A <> 'Ingrooves') THEN '75.83' 
	 WHEN EP2.PAY_CYCLE_HOURS IS NOT NULL THEN NULL
	  END STANDARD_HOURS,
EP.BUSINESS_TITLE JOB_TITLE,

CASE WHEN ESH.FREQUENCY = 'Annual' THEN CASE WHEN ESH.OPERATION = 'REMOVE' THEN '0' ELSE TO_CHAR(ESH.AMOUNT/24,'fm9999999.90') END
     WHEN ESH.FREQUENCY = 'Monthly' THEN CASE WHEN ESH.OPERATION = 'REMOVE' THEN '0' ELSE TO_CHAR(ESH.AMOUNT/2,'fm9999999.90') END END SALARY_PER_PAY,

EAI.ORGANIZATION_TWO_ID_C COST_CENTRE,
CASE WHEN EPE.PAYMENT_TYPE = 'Cheque' THEN 'C' 
	 --WHEN EPE.PAYMENT_TYPE = 'Deposit' THEN 'D' ELSE NULL END PAYMENT_TYPE,
	 WHEN EPE.PAYMENT_TYPE = 'Direct Deposit' THEN 'D' ELSE NULL END PAYMENT_TYPE,
--EPE.BANK_NAME BANK1,
EPE.BANK_ID_NUMBER BANK1,
EPE.BRANCH_ID_NUMBER BRANCH1,
--EPE.BRANCH_NAME BRANCH1,
EPE.ACCOUNT_NUMBER ACCOUNT1,
EPE.BANK_NAME BANK2,
EPE.BRANCH_NAME BRANCH2,
EPE.ACCOUNT_NUMBER ACCOUNT2,

EAI.ORGANIZATION_THREE_ID_C NEW_DEPARTMENT,

CASE WHEN ES.EMPLOYEE_STATUS = 'Terminated' AND ES.TERMINATION_DATE BETWEEN substr(A.PAY_PERIOD_START,1,10) AND SUBSTR(A.PAY_PERIOD_END,1,10)THEN 'YES' 
    WHEN ES.EMPLOYEE_STATUS = 'Terminated' AND ES.TERMINATION_DATE < substr(A.PAY_PERIOD_START,1,10)THEN 'NO' 
	WHEN ES.EMPLOYEE_STATUS IS NULL OR A.STAFFING_EVENT = 'RFL' THEN 'YES' 
	 WHEN A.STAFFING_EVENT = 'LOA' OR ES.EMPLOYEE_STATUS = 'OnPaidLeave' THEN 'YES'
	 WHEN ES.EMPLOYEE_STATUS = 'Active' THEN 'YES'
	 WHEN A.STAFFING_EVENT = 'LOA' OR ES.EMPLOYEE_STATUS = 'OnLeave' THEN 'NO'
	 end PAY_THIS_PERIOD_FLAG,

CASE WHEN COALESCE(EAI.BUSINESS_UNIT_REFERENCE_ID_C,EAI.BUSINESS_UNIT_REFERENCE_ID_A) LIKE '%Ingrooves%' OR COALESCE(EAI.BUSINESS_UNIT_NAME_C,EAI.BUSINESS_UNIT_NAME_A) LIKE '%Ingrooves%' THEN 'N' else 'H' END BRANCH,
NULL NEW_BRANCH
,CASE WHEN EAI.ORGANIZATION_THREE_ID_C IS NOT NULL OR EA.REGION IS NOT NULL OR EP.WORKER_TYPE IS NOT NULL THEN 'YES' ELSE 'NO' END ONE_TAX_FORM_FLAG
,EP.EFFECTIVE_DATE POS_EFFDT
,EP.WORKER_TYPE WORKER_TYPE
,ES1.HIRE_DATE OLD_HIREDT
/*,CASE WHEN EP.WORKER_TYPE = 'Fixed_Term' OR EP.WORKER_TYPE = 'Intern_Coop' THEN 2
      WHEN EP.WORKER_TYPE = 'Regular' AND MONTHS_BETWEEN(TO_DATE(EP.EFFECTIVE_DATE,'YYYY-MM-DD'),TO_DATE(ES1.HIRE_DATE,'YYYY-MM-DD')) <= 3 THEN 2 
      WHEN EP.WORKER_TYPE = 'Regular' AND MONTHS_BETWEEN(TO_DATE(EP.EFFECTIVE_DATE,'YYYY-MM-DD'),TO_DATE(ES1.HIRE_DATE,'YYYY-MM-DD')) > 3 THEN 1
      WHEN EP1.EMPLOYEE_ID IS NOT NULL AND EP.WORKER_TYPE = 'Regular' AND MONTHS_BETWEEN(TO_DATE(EP.EFFECTIVE_DATE,'YYYY-MM-DD'),TO_DATE(ES1.HIRE_DATE,'YYYY-MM-DD')) > 3 THEN 1
      ELSE CASE WHEN A.STAFFING_EVENT = 'TRM' THEN NULL ELSE 1  END END CCRA_BN_MRQ_ID*/
,CASE WHEN A.STAFFING_EVENT = 'TRM' THEN NULL ELSE 1 END CCRA_BN_MRQ_ID
,A.STAFFING_EVENT STAAFFING_EVENT
,ES.PRIMARY_TERMINATION_REASON PRIMARY_TERMINATION_REASON
,CASE WHEN A.STAFFING_EVENT = 'TRM' THEN 'TRM' 
      WHEN A.STAFFING_EVENT = 'RFL' THEN 'CHG'
      WHEN A.STAFFING_EVENT = 'LOA' OR ES.EMPLOYEE_STATUS = 'OnLeave' OR ES.EMPLOYEE_STATUS = 'OnPaidLeave' OR (EPL.ESTIMATED_LEAVE_END_DATE IS NOT NULL AND TO_DATE(EPL.ESTIMATED_LEAVE_END_DATE,'YYYY-MM-DD') >= TO_DATE(SUBSTR(PE.UPDATED_TO,1,10),'YYYY-MM-DD') )
	  THEN 'LOA'
	  WHEN A.STAFFING_EVENT = 'RFL' THEN 'CHG'
      ELSE 'CHG'
      END TYPE
,LKP4.REASON_CODE  ROE_REASON_CODE

FROM UMG_EMPLOYEE_MASTER_WORK A

LEFT JOIN EMPPERSONAL EPS ON A.PAY_GROUP_ID = EPS.PAY_GROUP_ID AND A.EMPLOYEE_ID = EPS.EMPLOYEE_ID AND EPS.EFFECTIVESTATUS = 'C'
AND EPS.MS$LOADID = A.MS$LOADID

LEFT JOIN UMG_EMP_ADD_INFO_WORK EAI ON A.PAY_GROUP_ID = EAI.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAI.EMPLOYEE_ID

LEFT JOIN EMPPAYMENTELECTION EPE ON A.PAY_GROUP_ID = EPE.PAY_GROUP_ID AND A.EMPLOYEE_ID = EPE.EMPLOYEE_ID AND EPE.EFFECTIVESTATUS = 'C'
AND EPE.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPIDENTIFIER EI ON A.PAY_GROUP_ID = EI.PAY_GROUP_ID AND A.EMPLOYEE_ID = EI.EMPLOYEE_ID AND EI.EFFECTIVESTATUS = 'C'
AND EI.IDENTIFIER_TYPE = 'Social Insurance Number (SVNR)' AND A.MS$LOADID = EI.MS$LOADID

LEFT JOIN EMPIDENTIFIER EI1 ON A.PAY_GROUP_ID = EI1.PAY_GROUP_ID AND A.EMPLOYEE_ID = EI1.EMPLOYEE_ID AND EI1.EFFECTIVESTATUS = 'C'
AND EI1.IDENTIFIER_TYPE = 'Social Insurance Number (SIN)' AND A.MS$LOADID = EI1.MS$LOADID

LEFT JOIN EMPIDENTIFIER EI2 ON A.PAY_GROUP_ID = EI2.PAY_GROUP_ID AND A.EMPLOYEE_ID = EI2.EMPLOYEE_ID AND EI2.EFFECTIVESTATUS = 'C'
 AND A.MS$LOADID = EI2.MS$LOADID


LEFT OUTER JOIN EMPADDRESSLINEDATA EAL1 ON (A.PAY_GROUP_ID = EAL1.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL1.EMPLOYEE_ID 
AND EAL1.EFFECTIVESTATUS = 'C' AND EAL1.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_1' AND EAL1.ADDRESSSEQUENCENUMBER = '1' AND A.MS$LOADID = EAL1.MS$LOADID)

LEFT OUTER JOIN EMPADDRESSLINEDATA EAL1A ON (A.PAY_GROUP_ID = EAL1A.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL1A.EMPLOYEE_ID 
AND EAL1A.EFFECTIVESTATUS = 'C' AND EAL1A.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_1' AND EAL1A.ADDRESSSEQUENCENUMBER = '2' AND A.MS$LOADID = EAL1A.MS$LOADID)

LEFT OUTER JOIN EMPADDRESSLINEDATA EAL2 ON (A.PAY_GROUP_ID = EAL2.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL2.EMPLOYEE_ID 
AND EAL2.EFFECTIVESTATUS = 'C' AND EAL2.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_2' AND EAL2.ADDRESSSEQUENCENUMBER = '1' AND A.MS$LOADID = EAL2.MS$LOADID)

LEFT OUTER JOIN EMPADDRESSLINEDATA EAL2A ON (A.PAY_GROUP_ID = EAL2A.PAY_GROUP_ID AND A.EMPLOYEE_ID = EAL2A.EMPLOYEE_ID 
AND EAL2A.EFFECTIVESTATUS = 'C' AND EAL2A.ADDRESS_LINE_DATA_TYPE = 'ADDRESS_LINE_2' AND EAL2A.ADDRESSSEQUENCENUMBER = '2' AND A.MS$LOADID = EAL2A.MS$LOADID)

LEFT JOIN EMPADDRESS EA ON A.PAY_GROUP_ID = EA.PAY_GROUP_ID AND A.EMPLOYEE_ID = EA.EMPLOYEE_ID AND EA.ADDRESSSEQUENCENUMBER = '1' AND EA.EFFECTIVESTATUS = 'C'
AND EA.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPADDRESS EA1 ON A.PAY_GROUP_ID = EA1.PAY_GROUP_ID AND A.EMPLOYEE_ID = EA1.EMPLOYEE_ID AND EA1.ADDRESSSEQUENCENUMBER = '2' AND EA1.EFFECTIVESTATUS = 'C'
AND EA1.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPPOSITION EP ON A.PAY_GROUP_ID = EP.PAY_GROUP_ID AND A.EMPLOYEE_ID = EP.EMPLOYEE_ID AND EP.EFFECTIVESTATUS = 'C'
AND EP.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPSTATUS ES ON A.PAY_GROUP_ID = ES.PAY_GROUP_ID AND A.EMPLOYEE_ID = ES.EMPLOYEE_ID AND ES.EFFECTIVESTATUS = 'C'
AND ES.MS$LOADID = A.MS$LOADID

LEFT JOIN UMG_SALARYHOURLYPLANS_W_WORK ESH ON A.PAY_GROUP_ID = ESH.PAY_GROUP_ID AND A.EMPLOYEE_ID = ESH.EMPLOYEE_ID AND A.MS$LOADID = ESH.MS$LOADID

LEFT JOIN EMPLEAVEOFABSENCE EPL ON A.PAY_GROUP_ID = EPL.PAY_GROUP_ID AND A.EMPLOYEE_ID = EPL.EMPLOYEE_ID AND EPL.EFFECTIVESTATUS = 'C'
AND A.MS$LOADID = EPL.MS$LOADID


LEFT JOIN TBL_PROVINCE_LKP LKP ON LKP.DESCRIPTION = NVL(EA1.REGION,EA.REGION)

LEFT JOIN TBL_REGION_LKP LKP1 ON LKP1.REGION_DESCRIPTION = NVL(EA1.REGION,EA.REGION)

--LEFT JOIN TBL_PROVN_EMPLYMNT_LKP LKP2 ON LKP2.PROVN_NAME = EA.REGION
LEFT JOIN TBL_PROVN_EMPLYMNT_LKP LKP2 ON LKP2.PROVN_NAME = EP.BUSINESS_SITE_REGION



LEFT JOIN TBL_EMP_CODE EMP ON A.EMPLOYEE_ID = EMP.EMPLOYEE_ID 

LEFT JOIN EMPSTATUS ES1 ON A.PAY_GROUP_ID = ES1.PAY_GROUP_ID AND A.EMPLOYEE_ID = ES1.EMPLOYEE_ID AND ES1.EFFECTIVESTATUS = 'A'
AND ES1.MS$LOADID = A.MS$LOADID

--LEFT JOIN EMPPOSITION EP1 ON A.PAY_GROUP_ID = EP1.PAY_GROUP_ID AND A.EMPLOYEE_ID = EP1.EMPLOYEE_ID AND EP1.EFFECTIVESTATUS = 'A'
--AND EP1.WORKER_TYPE = 'Fixed_Term' AND EP1.MS$LOADID = A.MS$LOADID

LEFT JOIN EMPPOSITION EP2 ON A.PAY_GROUP_ID = EP2.PAY_GROUP_ID AND A.EMPLOYEE_ID = EP2.EMPLOYEE_ID AND EP2.EFFECTIVESTATUS = 'A' AND EP2.OPERATION <> 'REMOVE'
AND EP2.MS$LOADID = A.MS$LOADID

LEFT JOIN LKP_ROE_REASON_CODE LKP4 ON ES.PRIMARY_TERMINATION_REASON = LKP4.TERMINATION_REASON_WORKDAY
--LEFT JOIN TBL_PAYROLLTYPE_LKP LKP3 ON LKP3.PAYROLL_TYPE = CASE WHEN ESH.AMOUNT IS NOT NULL THEN COALESCE(EP.PAY_RATE_TYPE,EP2.PAY_RATE_TYPE) END 
--LEFT JOIN TBL_PAYROLLTYPE_LKP LKP3 ON LKP3.PAYROLL_TYPE = EP.PAY_RATE_TYPE
LEFT JOIN TBL_PAYROLLTYPE_LKP LKP3 ON LKP3.PAYROLL_TYPE = ESH.FREQUENCY

LEFT JOIN PAYROLLEXTRACT PE ON A.PAY_GROUP_ID = PE.PAY_GROUP_ID

WHERE ((COALESCE(A.STAFFING_EVENT,CAST('NULL' AS NVARCHAR2(5))) NOT IN ('HIR','PGI','PCI','PCO') AND 
(EPL.ESTIMATED_LEAVE_END_DATE IS NOT NULL OR/*Uncomment leave end date since it is required 08jum23 by tamil*/ COALESCE(EPS.FIRST_NAME,EAI.FIRST_NAME_C) IS NOT NULL OR EPS.LAST_NAME IS NOT NULL OR EPS.BIRTH_DATE IS NOT NULL OR EAI.ORGANIZATION_ONE_NAME_C IS NOT NULL OR
EAI.ORGANIZATION_TWO_ID_C IS NOT NULL OR EI.IDENTIFIER_TYPE IS NOT NULL OR EAL1.ADDRESS_LINE_DATA IS NOT NULL OR EA.MUNICIPALITY IS NOT NULL OR
EA.POSTAL_CODE IS NOT NULL OR EAI.HIRE_DATE_C IS NOT NULL OR EPS.PREFERRED_LANGUAGE  IS NOT NULL OR LKP.CODE IS NOT NULL OR
/*ES.EMPLOYEE_STATUS IS NOT NULL OR*/ ES.TERMINATION_DATE IS NOT NULL OR EP.PAY_RATE_TYPE IS NOT NULL OR LKP2.PROVN_CODE IS NOT NULL OR LKP1.REGION_CODE IS NOT NULL OR
EP.PAY_CYCLE_HOURS IS NOT NULL OR EP.SCHEDULED_WEEKLY_HOURS IS NOT NULL OR EAI.ORGANIZATION_THREE_NAME_C IS NOT NULL OR EPE.PAYMENT_TYPE IS NOT NULL OR
EPE.BANK_NAME IS NOT NULL OR EPE.BRANCH_NAME IS NOT NULL OR EPE.ACCOUNT_NUMBER IS NOT NULL OR EAI.ORGANIZATION_TWO_ID_C IS NOT NULL OR ESH.AMOUNT IS NOT NULL
OR EP.BUSINESS_TITLE IS NOT NULL OR EAI.ORGANIZATION_THREE_ID_C IS NOT NULL OR /*ES.EMPLOYEE_STATUS IS NOT NULL OR EP.WORKER_TYPE IS NOT NULL OR*/ EP.EFFECTIVE_DATE IS NOT NULL
OR ES.PRIMARY_TERMINATION_REASON IS NOT NULL OR EI2.IDENTIFIER_TYPE IS NOT NULL OR EI2.IDENTIFIER_value IS NOT NULL /*OR ESH1.AMOUNT IS NOT NULL */ --06-mar-23 
))
)